services:
  - docker

script:
  - docker build -t gregoireweber/minecraft-map-builder:latest map-builder/
  - docker build -t gregoireweber/minecraft-map-viewer:latest map-viewer/
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag gregoireweber/minecraft-map-builder:latest gregoireweber/minecraft-map-builder:0.16.0;
      docker tag gregoireweber/minecraft-map-builder:latest gregoireweber/minecraft-map-builder:0.16.0-"$TRAVIS_BUILD_NUMBER";
      docker tag gregoireweber/minecraft-map-viewer:latest gregoireweber/minecraft-map-viewer:"$TRAVIS_BUILD_NUMBER";
      docker push gregoireweber/minecraft-map-builder:latest;
      docker push gregoireweber/minecraft-map-builder:0.16.0;
      docker push gregoireweber/minecraft-map-builder:0.16.0-"$TRAVIS_BUILD_NUMBER";
      docker push gregoireweber/minecraft-map-viewer:latest;
      docker push gregoireweber/minecraft-map-viewer:"$TRAVIS_BUILD_NUMBER";
    fi