version: '3.7'

services:

  minecraft-server:
    image: gregoireweber/minecraft-server:latest
    restart: unless-stopped
    volumes:
    - ./server-data:/minecraft/data
    ports:
     - "25565:25565"
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "30"

  minecraft-map-builder:
    image: gregoireweber/minecraft-map-builder:latest
    restart: unless-stopped
    volumes:
      - './server-data:/home/minecraft/server'
      - './render-data:/home/minecraft/sharedRender'
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"

  minecraft-map-viewer:
    image: gregoireweber/minecraft-map-viewer:latest
    restart: unless-stopped
    volumes:
      - './render-data:/home/minecraft/render'
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"
